name: euro_explorer
description: "A Flutter application to explore European countries with wishlist functionality."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & Caching
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.0
  
  # State Management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.5
  
  # Local Database
  drift: ^2.19.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # UI & Utils
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  equatable: ^2.0.5
  get_it: ^7.6.7
  
  # Code Generation
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  very_good_analysis: ^5.1.0
  
  # Testing
  mocktail: ^1.0.3
  bloc_test: ^9.1.5
  drift_dev: ^2.19.0
  
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
